import type { Metadata } from "next";
import { Noto_Sans_Lao } from "next/font/google";
import "./globals.css";

//import context
import SidebarProvider from "../context/Sidebar";

//import component
import Sidebar from "./component/Sidebar";
import Header from "./component/Header";

//font
const notoSans = Noto_Sans_Lao({
    subsets: ["lao", "latin"],
    weight: ["400", "700"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <SidebarProvider>
                <body
                    className={`${notoSans.className} bg-gray-900 text-white`}
                >
                    <main className="flex h-screen">
                        <Sidebar />
                        <div className="flex-1 flex flex-col">
                            <Header />
                            <div className="flex-1 overflow-auto">
                                {children}
                            </div>
                        </div>
                    </main>
                </body>
            </SidebarProvider>
        </html>
    );
}
